/* Public, versioned local assets only. Rooms/auth/API traffic always uses the network. */
importScripts('./assets/asset-manifest.js');
const ROOT=new URL('./',self.location.href),CACHE_NAME='ml-static-v1:'+ROOT.href,flights=new Map();
function assetPath(url){const u=new URL(url,ROOT);if(u.origin!==ROOT.origin||!u.pathname.startsWith(ROOT.pathname))return null;const path=u.pathname.slice(ROOT.pathname.length);return Object.hasOwn(ASSET_REVISIONS,path)?path:null}
function assetKey(path,search=''){const key=new URL(path,ROOT);key.search=new URLSearchParams(search).get('rev')===ASSET_REVISIONS[path]?'':search;key.searchParams.set('__revision',ASSET_REVISIONS[path]);return key.href}
async function loadAsset(path,search=''){const flightKey=assetKey(path,search);if(flights.has(flightKey))return flights.get(flightKey);const flight=(async()=>{const cache=await caches.open(CACHE_NAME).catch(()=>null),key=assetKey(path,search),hit=cache&&await cache.match(key).catch(()=>null);if(hit)return hit;const response=await fetch(new URL(path+search,ROOT).href,{cache:'no-cache',credentials:'same-origin'});if(response.ok&&response.type!=='opaque'&&cache)await cache.put(key,response.clone()).catch(()=>{});return response})();flights.set(flightKey,flight);try{return await flight}finally{flights.delete(flightKey)}}
self.addEventListener('install',event=>event.waitUntil(self.skipWaiting()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE_NAME).catch(()=>null);if(cache){for(const request of await cache.keys()){const path=assetPath(request.url);if(!path||new URL(request.url).searchParams.get('__revision')!==ASSET_REVISIONS[path])await cache.delete(request).catch(()=>{})}}await self.clients.claim()})()));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET'||event.request.headers.has('range'))return;const path=assetPath(event.request.url);if(path)event.respondWith(loadAsset(path,new URL(event.request.url).search).then(response=>response.clone()))});
self.addEventListener('message',event=>{if(event.data?.type!=='CACHE_ASSETS'||!event.ports[0])return;const port=event.ports[0],source=event.source?.url;if(!source||new URL(source).origin!==ROOT.origin)return;const paths=event.data.allImages?IMAGE_ASSETS:[...new Set((Array.isArray(event.data.paths)?event.data.paths:[]).filter(p=>typeof p==='string'&&assetPath(p)))].slice(0,80);event.waitUntil((async()=>{let index=0,completed=0,failed=0;const cache=await caches.open(CACHE_NAME).catch(()=>null);async function run(){while(index<paths.length){const url=new URL(paths[index++],ROOT),path=assetPath(url.href),search=url.search;try{const response=await loadAsset(path,search);if(!response.ok||!cache||!await cache.match(assetKey(path,search)))failed++}catch{failed++}completed++;port.postMessage({completed,total:paths.length,failed,done:false})}}await Promise.all([run(),run()]);port.postMessage({completed,total:paths.length,failed,done:true})})())});
