import {createAccountSession} from '../assets/account/session.mjs';
const $=id=>document.getElementById(id);
let client=null,index=[],images={},edits=new Map(),reports=[],selected=null,loadedUID=null,flight=false;
const status=text=>{$('editorStatus').textContent=text};
async function api(action,data={}){return client.authorized('/rest/v1/rpc/ml_content_editor',{p_action:action,p_data:data})}
function node(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n}
function validURL(text){return /^https:\/\//.test(text)}
async function init(){try{const [base,html]=await Promise.all([fetch('../content/catalogue-index.json').then(r=>{if(!r.ok)throw Error('Katalog fehlt');return r.json()}),fetch('../index.html').then(r=>r.text())]);index=base.rows;images=base.images;const url=html.match(/const SUPABASE_URL=['"]([^'"]+)/)?.[1]||html.match(/SUPABASE_URL\s*=\s*['"]([^'"]+)/)?.[1],key=html.match(/(?:const\s+)?KEY\s*=\s*['"]([^'"]+)/)?.[1];if(!url||!key)throw Error('Projektverbindung fehlt');connection={url,key};client=createAccountSession({url,key,storage:localStorage});paintImages();await load()}catch(e){status(e.message)}}
async function load(){const auth=await client.current();if(!auth||auth.guest){loadedUID=null;status('Melde dich mit einem bestätigten Redaktionskonto an. Lokale Entwürfe bleiben ohne Anmeldung nutzbar.');return}loadedUID=auth.uid;$('editorIdentity').textContent='Konto-ID: '+auth.uid;try{const data=await api('list');edits=new Map(data.entries.map(e=>[e.id,e]));reports=data.reports;paintQuestions();paintReports();status('Redaktion geladen · '+reports.filter(r=>r.review_status==='open').length+' offene Meldungen.')}catch(e){status(e.message+' · Nutze zur ersten Freischaltung den einmaligen Code.')}}
$('editorLogin').onsubmit=async event=>{event.preventDefault();if(flight)return;flight=true;try{await client.login($('editorEmail').value.trim(),$('editorPassword').value);$('editorPassword').value='';await load()}catch(e){status(e.message)}finally{flight=false}};
$('editorRegister').onclick=async()=>{try{const result=await client.registerNew($('editorEmail').value.trim(),$('editorPassword').value,location.origin+location.pathname);$('editorPassword').value='';status(result.confirmationRequired?'Bestätige deine E-Mail und melde dich danach an.':'Account erstellt.');if(!result.confirmationRequired)await load()}catch(e){status(e.message)}};
$('editorLogout').onclick=async()=>{await client.logout();edits.clear();reports=[];selected=null;loadedUID=null;$('editorQuestions').replaceChildren();$('editorReports').replaceChildren();$('editorForm').hidden=true;$('editorIdentity').textContent='';status('Abgemeldet.');};
$('editorActivate').onclick=async()=>{try{await client.authorized('/rest/v1/rpc/ml_activate_editor',{p_code:$('editorCode').value.trim()});$('editorCode').value='';await load()}catch(e){status(e.message)}};
$('editorReload').onclick=()=>load().catch(e=>status(e.message));$('editorSearch').oninput=paintQuestions;
function paintQuestions(){const list=$('editorQuestions');list.replaceChildren();const filter=$('editorSearch').value.toLowerCase(),all=new Map(index.map(r=>[r.id,r]));for(const e of edits.values())all.set(e.id,e);const hits=[...all.values()].filter(r=>(r.payload.q||r.payload.s||r.payload.l+' / '+r.payload.r).toLowerCase().includes(filter));for(const r of hits.slice(0,80)){const b=node('button',(r.payload.q||r.payload.s||r.payload.l+' / '+r.payload.r)+' · '+r.game+(edits.has(r.id)?' · '+edits.get(r.id).status:''));b.type='button';b.onclick=()=>selectQuestion(r.id);list.append(b)}$('editorCount').textContent=hits.length+' Treffer · angezeigt bis zu 80'}
function selectQuestion(id){const row=edits.get(id)||index.find(r=>r.id===id);if(!row)return;selected={...row,payload:{...row.payload}};$('editorForm').hidden=false;$('editorContentId').textContent=id;const form=$('editorForm'),q=selected.payload;form.elements.game.value=selected.game;for(const key of ['q','s','l','r','a','e','u','metric','cat','subject','source','verified','as_of','difficulty','lv','rv'])form.elements[key].value=q[key]??'';form.elements.disabled.checked=!!selected.disabled;form.elements.time_dependent.checked=!!q.time_dependent;updateFields();form.scrollIntoView({block:'nearest'})}
function updateFields(){const game=$('editorForm').elements.game.value;for(const field of document.querySelectorAll('[data-games]'))field.hidden=!field.dataset.games.split(' ').includes(game)}
$('editorForm').elements.game.onchange=()=>{if(!selected?.isNew||selected?.version){$('editorForm').elements.game.value=selected.game;return}updateFields()};
$('editorNew').onclick=()=>{selected={id:'estimate:'+crypto.randomUUID().replaceAll('-',''),game:'estimate',isNew:true,payload:{source:'',verified:new Date().toISOString().slice(0,10),cat:'Allgemeinwissen'}};edits.set(selected.id,selected);selectQuestion(selected.id)};
$('editorForm').onsubmit=async event=>{event.preventDefault();if(flight||!selected)return;flight=true;const form=$('editorForm');try{if((await client.current())?.uid!==loadedUID)throw Error('Account gewechselt. Bitte neu laden.');const game=form.elements.game.value,q={...selected.payload};for(const key of ['q','s','l','r','e','u','metric','cat','subject','source','verified','as_of'])q[key]=form.elements[key].value.trim();if(!validURL(q.source))throw Error('HTTPS-Quelle erforderlich');q.time_dependent=form.elements.time_dependent.checked;if(q.time_dependent&&!q.as_of)throw Error('Datenstand für veränderliche Fakten erforderlich');q.a=game==='facts'?form.elements.a.value==='true':game==='estimate'?Number(form.elements.a.value):form.elements.a.value.trim();if(game==='estimate'&&!form.elements.a.value.trim())throw Error('Zahlenwert erforderlich');if(game==='facts'&&!['true','false'].includes(form.elements.a.value))throw Error('Antwort muss true oder false sein');if(game==='moreless'){if(!form.elements.lv.value.trim()||!form.elements.rv.value.trim())throw Error('Beide Werte erforderlich');q.lv=Number(form.elements.lv.value);q.rv=Number(form.elements.rv.value)}q.difficulty=game==='jeopardy'?Number(form.elements.difficulty.value)||2:form.elements.difficulty.value||'medium';const row=await api('save',{id:selected.id,game,payload:q,disabled:form.elements.disabled.checked,version:selected.version||0});edits.set(row.id,row);selected=row;paintQuestions();status('Entwurf gespeichert. Veröffentlichung ist ein eigener Schritt.')}catch(e){status(e.message)}finally{flight=false}};
$('editorPublish').onclick=async()=>{if(flight||!selected?.version){status('Speichere zuerst den Entwurf.');return}flight=true;try{const row=await api('publish',{id:selected.id,version:selected.version});edits.set(row.id,row);selected=row;paintQuestions();status('Veröffentlicht ✓ Beim nächsten Öffnen der Spielseite wird die Änderung geladen. Bereits laufende Fragen behalten ihren Stand.')}catch(e){status(e.message)}finally{flight=false}};
function paintReports(){const list=$('editorReports');list.replaceChildren();for(const r of reports){const card=node('section'),h=node('h3',r.prompt),detail=node('p',r.reason+' · '+r.note),select=node('select'),note=node('textarea');select.setAttribute('aria-label','Bearbeitungsstatus');for(const [value,label] of [['open','Offen'],['reviewing','In Prüfung'],['resolved','Erledigt'],['dismissed','Verworfen']]){const o=node('option',label);o.value=value;select.append(o)}select.value=r.review_status;note.value=r.review_note;note.maxLength=1000;note.setAttribute('aria-label','Redaktionelle Entscheidung');const b=node('button','Entscheidung speichern');b.onclick=async()=>{b.disabled=true;try{const result=await api('report',{id:r.id,status:select.value,note:note.value});Object.assign(r,result);status('Meldung bearbeitet ✓')}catch(e){status(e.message)}finally{b.disabled=false}};const search=node('button','Passende Frage öffnen');search.onclick=()=>{if(index.some(q=>q.id===r.question_key)||edits.has(r.question_key)){selectQuestion(r.question_key)}else{$('editorSearch').value=r.prompt.split(' · ')[0];paintQuestions();$('editorSearch').focus()}};card.append(h,detail,select,note,b,search);list.append(card)}}
function paintImages(){const list=$('editorImages');list.replaceChildren();for(const [name,image] of Object.entries(images)){const issues=[];if(!image.source||!image.license)issues.push('Nachweis fehlt');if(image.generated)issues.push('Illustration');if(!image.detail)issues.push('Fragezuschnitt fehlt');if(image.card.endsWith('.svg'))issues.push('Beschriftung prüfen');const d=node('details'),s=node('summary',name+' · '+(issues.join(' · ')||'Nachweis vorhanden'));d.append(s);for(const [kind,ratio] of [['card','4 / 3'],['detail','16 / 9']]){const img=node('img');img.src='../assets/visuals/'+image[kind];img.alt=name+' · '+kind;img.loading='lazy';img.style.aspectRatio=ratio;img.style.objectFit='cover';d.append(img)}d.append(node('p',image.license));const a=node('a','Bildquelle ↗');a.href=image.source;a.target='_blank';a.rel='noopener noreferrer';d.append(a,node('p','Manuell prüfen: Motiv erkennbar? Zuschnitt passend? Zahlen oder Text verraten keine Lösung?'));list.append(d)}}
$('editorUpload').onclick=async()=>{try{if(!selected)throw Error('Zuerst eine Frage wählen.');const file=$('editorImageFile').files[0],credit=$('editorImageSource').value.trim(),license=$('editorImageLicense').value.trim(),subject=$('editorImageSubject').value.trim();if(!file||!validURL(credit)||!license||!subject)throw Error('Bild, Motiv, HTTPS-Quelle und Lizenz erforderlich.');if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10000000)throw Error('PNG, JPEG oder WebP bis 10 MB verwenden.');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,960/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.82));if(!blob||blob.size>1500000)throw Error('Bild ist nach Verkleinerung noch zu groß.');const auth=await client.current(),path=auth.uid+'/'+crypto.randomUUID()+'.webp',saved=JSON.parse(localStorage.getItem('ml_account_auth_v1')),url=clientURL();const response=await fetch(url+'/storage/v1/object/editorial-images/'+path,{method:'POST',headers:{apikey:clientKey(),Authorization:'Bearer '+saved.token,'Content-Type':'image/webp'},body:blob});if(!response.ok)throw Error('Upload abgelehnt. Redaktionsrechte prüfen.');$('editorForm').elements.subject.value=subject;selected.payload.content_image={subject,url:url+'/storage/v1/object/public/editorial-images/'+path,source:credit,license,focus:[.5,.5]};status('Bild hochgeladen. Speichere und veröffentliche die Frage, um es im Spiel zu verwenden.')}catch(e){status(e.message)}};
let connection=null;function clientURL(){return connection.url}function clientKey(){return connection.key}
init();
