"""Additional distinct measures in every More/Less category and authored Jeopardy clues."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DATE='2026-10-04'
rows=json.loads((ROOT/'content/catalogue.json').read_text()); trivia=json.loads((ROOT/'content/trivia.json').read_text())
for r in rows: r['facts']=[f for f in r['facts'] if f.get('expansion')!=6]
trivia['jeopardy']=[q for q in trivia['jeopardy'] if q.get('expansion')!=6]
newfacts=[]; clues=[]
def numeric(name,cat,metric,value,unit,source,notes=''):
 r=next(r for r in rows if r['name']==name)
 f=dict(category=cat,metric=metric,value=value,unit=unit,comparison_unit=f'{unit} · {metric}',source=source,verified=DATE,expansion=6,notes=notes,estimate_question=f'{name}: Wie hoch ist der Wert für „{metric}“ ({unit})?')
 r['facts'].append(f);newfacts.append(dict(subject=name,**f))
def clue(cat,q,a,source,d=2):
 clues.append(dict(cat=cat,q=q,a=str(a),source=source,verified=DATE,difficulty=d,expansion=6))
ITU='https://www.itu.int/oth/t0202/en'
for n,v in [('Österreich',43),('Schweiz',41),('Belgien',32)]: numeric(n,'Länder','Internationale Telefon-Landeskennzahl',v,'Zahl nach +',ITU,'Telefonvorwahl ohne internationale Verkehrsausscheidungsziffer.')
for n,v,s in [('Berlin',891.1,'https://bundeswahlleiterin.de/bundestagswahlen/2025/strukturdaten/bund-99/land-11.html'),('Hamburg',755,'https://www.hamburg.de/politik-und-verwaltung/behoerden/bukea/themen/boden-und-geologie/altlasten/flaechenrecycling/flaechenrecycling-167942'),('Wien',414.9,'https://www.wien.gv.at/statistik/aktuelle-daten')]: numeric(n,'Städte','Stadtfläche laut angegebenem Quellenstand',v,'km²',s,'Berlin: 31.12.2023; Hamburg: gerundeter Behördenwert; Wien: 2025. Verwaltungsfläche einschließlich Wasserflächen.')
for n,v,s in [('Eiffelturm',1887,'https://www.toureiffel.paris/en/the-monument/history'),('Empire State Building',1930,'https://www.esbnyc.com/about/history'),('Burj Khalifa',2004,'https://bk.emaar.com/en/assets/FACT-SHEET.pdf')]: numeric(n,'Bauwerke','Baubeginn (einschließlich Gründungsarbeiten)',v,'Jahr',s)
for n,v,s in [('Yellowstone-Nationalpark',2221766,'https://www.nps.gov/yell/planyourvisit/parkfacts.htm'),('Yosemite-Nationalpark',759620,'https://www.nps.gov/yose/learn/management/statistics.htm'),('Grand-Canyon-Nationalpark',1218375,'https://home.nps.gov/grca/learn/management/statistics.htm')]: numeric(n,'Natur','Parkfläche laut NPS-Statistik',v,'Acres',s,'Momentaufnahme der verlinkten NPS-Statistik; verschiedene ältere NPS-Unterseiten können abweichende Grenzstände enthalten.')
for n,v,slug in [('Elefant',120,'elephant'),('Giraffe',100,'giraffe'),('Löwe',1.4,'lion')]: numeric(n,'Tierwelt','Geburtsgewicht: oberer genannter Richtwert',v,'kg',f'https://animals.sandiegozoo.org/animals/{slug}','Oberes Ende des Zoo-Richtbereichs; beim Löwen einzelner ungefährer Wert. Kein Durchschnitt und kein Rekord.')
for n,v,slug in [('Kohlenstoff',12.011,'6/carbon'),('Sauerstoff',15.999,'8/oxygen'),('Eisen',55.845,'26/iron')]: numeric(n,'Wissenschaft','Relative Atommasse nach RSC',v,'relative Atommasse',f'https://periodic-table.rsc.org/element/{slug}','Dimensionsloser Tabellenwert; keine Massenzahl eines einzelnen Isotops.')
for n,v,s in [('Fußball',90,'https://www.theifab.com/laws/latest/the-duration-of-the-match/'),('Basketball',40,'https://assets.fiba.basketball/image/upload/documents-corporate-fiba-official-rules-2026-v1-1.pdf'),('Hallenhandball',60,'https://www.ihf.info/sites/default/files/2025-02/09A%20-%20Rules%20of%20the%20Game_Indoor%20Handball_E.pdf')]: numeric(n,'Sport','Reguläre Spielzeit für Erwachsene ohne Verlängerung',v,'Minuten',s,'Fußball ohne Nachspielzeit; Basketball nach FIBA, nicht NBA; Handball für mindestens 16-Jährige.')
for n,v,s in [('Porsche 911 GT3 (PDK, 2025)',450,'https://newsroom.porsche.com/en/2024/products/porsche-the-new-911-gt3-double-premiere-37595.html'),('Ferrari 296 GTB',740,'https://www.ferrari.com/content/dam/ferrari-fcom/old/pdf/CS_296_GTB_final_gbr.pdf'),('Ferrari SF90 Stradale',800,'https://cdn.ferrari.com/cms/network/media/pdf/pr_ferrari_sf90_stradale_gbr.pdf')]: numeric(n,'Autos','Maximales Drehmoment des Verbrennungsmotors',v,'Nm',s,'Verbrennungsmotor, kein addiertes Hybrid-Systemdrehmoment.')
for n,v,s in [('Aachener Dom',.223,'https://whc.unesco.org/en/list/3/'),('Opernhaus Sydney',5.8,'https://whc.unesco.org/en/list/166/')]: numeric(n,'Weltkultur','UNESCO-Kernfläche ohne Pufferzone',v,'ha',s,'Property, nicht Buffer zone; Quellenstand 4.10.2026.')
for n,v,s in [('Standard-Kartendeck ohne Joker',4,'https://de.bicyclecards.com/game-rules/spades/'),('SET (Grundspiel)',3,'https://www.setgame.com/sites/default/files/teacherscorner/THE%20JOY%20OF%20SET.pdf')]: numeric(n,'Allgemeinwissen','Anzahl der Kartenfarben',v,'Kartenfarben',s,'Standarddeck: vier Farben/Suits; SET: rot, grün, violett. Keine Anzahl der Farbpigmente einer Druckdatei.')
for n,dist in [('400-m-Weltrekord Männer',400),('800-m-Weltrekord Männer',800),('1500-m-Weltrekord Männer',1500)]:
 r=next(r for r in rows if r['name']==n);f=r['facts'][0]
 numeric(n,'Rekorde & Extreme','Mittlere Geschwindigkeit des Rekordlaufs · WA September 2026',round(dist/f['value'],3),'m/s',f['source'],'Berechnet als Streckenlänge geteilt durch die veröffentlichte Rekordzeit; auf drei Dezimalstellen gerundet. Historischer Quellenstand September 2026.')
for n,v,s in [('Sputnik 1',83,'https://science.nasa.gov/blogs/earth-matters/2017/04/14/modern-satellites-littler-and-mightier-than-before/'),('Explorer 1',14,'https://science.nasa.gov/blogs/earth-matters/2017/04/14/modern-satellites-littler-and-mightier-than-before/'),('James-Webb-Weltraumteleskop',6200,'https://www.esa.int/Science_Exploration/Space_Science/Webb/Webb_factsheet')]: numeric(n,'Raumfahrt','Masse beim Start laut Quelle, ungefähr',v,'kg',s,'NASA gerundete Satellitenwerte; Webb einschließlich Verbrauchsmitteln und Startadapter nach ESA.')
numeric('Kölner Dom','Weltkultur','UNESCO-Kernfläche ohne Pufferzone',.874,'ha','https://whc.unesco.org/en/list/292/','Property, nicht Buffer zone; Quellenstand 4.10.2026.')
for n,cc,rpm,source in [('Porsche 911 GT3 (PDK, 2025)',3996,9000,'https://newsroom.porsche.com/en/press-kits/911-GT3/Powertrain-and-performance.html'),('Ferrari 296 GTB',2992,8500,'https://www.ferrari.com/content/dam/ferrari-fcom/old/pdf/CS_296_GTB_final_gbr.pdf'),('Ferrari SF90 Stradale',3990,8000,'https://cdn.ferrari.com/cms/network/media/pdf/pr_ferrari_sf90_stradale_gbr.pdf')]:
 numeric(n,'Autos','Hubraum des Verbrennungsmotors',cc,'cm³',source)
 numeric(n,'Autos','Maximale Motordrehzahl des Verbrennungsmotors',rpm,'U/min',source)
# Jeopardy: these are distinct measures from the already imported clues.
catmap={'Länder':'Geografie','Städte':'Geografie','Bauwerke':'Geschichte','Natur':'Nationalparks','Tierwelt':'Allgemeinwissen','Wissenschaft':'Chemie','Sport':'Sportregeln','Autos':'Autotechnik','Weltkultur':'Weltkultur','Allgemeinwissen':'Mix','Rekorde & Extreme':'Rekorde & Extreme','Raumfahrt':'Raumfahrtmissionen'}
for i,f in enumerate(newfacts): clue(catmap[f['category']],f['estimate_question'],str(f['value'])+'|'+str(f['value']).replace('.',',')+'|'+f"{f['value']} {f['unit']}",f['source'],min(5,2+i%4))
NIST='https://www.nist.gov/pml/special-publication-330/sp-330-section-2'
for i,(quantity,unit) in enumerate([('Frequenz','Hertz'),('Kraft','Newton'),('Druck','Pascal'),('Energie','Joule'),('Leistung','Watt'),('elektrische Ladung','Coulomb'),('elektrischen Widerstand','Ohm'),('elektrische Kapazität','Farad'),('magnetischen Fluss','Weber'),('magnetische Flussdichte','Tesla'),('Induktivität','Henry'),('Lichtstrom','Lumen'),('Beleuchtungsstärke','Lux')]): clue('Wissenschaft',f'Welche SI-Einheit mit eigenem Namen verwendet man für {quantity}?',unit,NIST,1+i%5)
GER='https://www.deutschland.de/de/topic/leben/mobilitaet-reise/landeshauptstaedte'
for i,(state,capital) in enumerate([('Baden-Württemberg','Stuttgart'),('Brandenburg','Potsdam'),('Hessen','Wiesbaden'),('Niedersachsen','Hannover'),('Nordrhein-Westfalen','Düsseldorf'),('Rheinland-Pfalz','Mainz'),('Saarland','Saarbrücken'),('Sachsen','Dresden'),('Sachsen-Anhalt','Magdeburg'),('Schleswig-Holstein','Kiel'),('Thüringen','Erfurt')]): clue('Deutschland',f'Wie heißt die Landeshauptstadt von {state}?',capital,GER,1+i%4)
GUT='https://www.gutenberg.org/ebooks/bookshelf/649'
for title,author in [('Alice im Wunderland','Lewis Carroll'),('Frankenstein','Mary Shelley'),('Dracula','Bram Stoker'),('Moby Dick','Herman Melville')]: clue('Kultur',f'Wer schrieb den Roman „{title}“?',author,GUT,2)
OLY='https://worldathletics.org/results/olympic-games'
for i,(year,city) in enumerate([(2024,'Paris'),(2020,'Tokio'),(2016,'Rio de Janeiro'),(2012,'London'),(2008,'Peking'),(2004,'Athen'),(2000,'Sydney'),(1996,'Atlanta'),(1992,'Barcelona'),(1988,'Seoul')]): clue('Sport',f'Welche Stadt war Gastgeberin der Olympischen Sommerspiele {year}'+(' (ausgetragen 2021)' if year==2020 else '')+'?',city,OLY,1+i%5)
UEFA='https://es.uefa.com/news/0252-0e98d341867a-1f3b773dccf1-1000--todas-las-finales-en-video/'
for i,(year,club) in enumerate([(2025,'Paris Saint-Germain'),(2024,'Real Madrid'),(2023,'Manchester City'),(2021,'Chelsea'),(2020,'Bayern München'),(2019,'Liverpool'),(2015,'Barcelona'),(2010,'Inter Mailand'),(2008,'Manchester United'),(2004,'FC Porto'),(1995,'Ajax Amsterdam'),(1993,'Olympique Marseille')]): clue('Champions League',f'Welcher Verein gewann das Männer-Champions-League-Finale {year}?',club,UEFA,1+i%5)
WHO='https://www.doctorwho.tv/news-and-features/what-is-a-time-lord'
for q,a,d in [('Von welchem Planeten stammen die Time Lords in Doctor Who?','Gallifrey',2),('Wie viele Herzen hat ein Time Lord normalerweise?','2',1),('Wie heißt die Veränderung des Körpers, mit der Time Lords dem Tod entgehen können?','Regeneration',2),('Wie viele Sonnen umkreist Gallifrey laut Doctor Who?','2',4),('Wie heißt das Sternsystem, in dem Gallifrey liegt?','Kasterborous',5),('Wie viele Regenerationen umfasst ein gewöhnlicher Time-Lord-Zyklus maximal?','12',4)]: clue('Science-Fiction',q,a,WHO,d)
clue('Science-Fiction','Wofür steht die englische Abkürzung TARDIS?','Time and Relative Dimension in Space','https://www.doctorwho.tv/news-and-features/what-is-the-tardis',4)
clue('Science-Fiction','In welchem Jahr lief die erste Doctor-Who-Geschichte „An Unearthly Child“?','1963','https://www.doctorwho.tv/news-and-features/what-is-the-tardis',3)
clue('Science-Fiction','Auf welchem Planeten entstanden die Daleks?','Skaro','https://www.doctorwho.tv/news-and-features/a-brief-history-of-the-daleks',3)
clue('Science-Fiction','Wie heißt Spocks Vater in Star Trek?','Sarek','https://www.startrek.com/en-un/news/most-memorable-dads',3)
SW='https://www.starwars.com/databank/r2-d2'
for q,a,d in [('Zu welcher Droidenklasse gehört R2-D2?','Astromech-Droide',2),('Wer versteckte die Todessternpläne in R2-D2?','Leia Organa',2),('An welchen Jedi war Leias Hilfsbotschaft in Episode IV gerichtet?','Obi-Wan Kenobi',2),('Welcher Feuchtigkeitsfarmer kaufte R2-D2 und C-3PO den Jawas ab?','Owen Lars',3),('Welcher Verbrecher erhielt den in Karbonit eingefrorenen Han Solo?','Jabba der Hutt',2),('Auf welchem Waldmond befindet sich der Schildgenerator des zweiten Todessterns?','Endor',2),('Welches Lichtschwert schmuggelte R2-D2 in Jabbas Palast?','Luke Skywalkers Lichtschwert',3)]: clue('Star Wars',q,a,SW,d)
clue('Star Wars','Welche Art Droide ist C-3PO?','Protokolldroide','https://www.starwars.com/databank/c-3po',1)
clue('Star Wars','Zu welcher Spezies gehört Chewbacca?','Wookiee','https://www.starwars.com/databank/chewbacca',1)
clue('Star Wars','Welche Kristalle bilden das Herz eines Jedi-Lichtschwerts?','Kyberkristalle','https://www.starwars.com/databank/lightsaber-crystal',3)
NASA='https://nssdc.gsfc.nasa.gov/planetary/factsheet/'
for q,a,d in [('Welcher Planet hat laut NASA die höchste mittlere Dichte?','Erde',3),('Welcher Planet hat laut NASA die niedrigste mittlere Dichte?','Saturn',2),('Welcher Planet bewegt sich auf seiner Bahn im Mittel am schnellsten?','Merkur',2),('Welcher Planet bewegt sich auf seiner Bahn im Mittel am langsamsten?','Neptun',2),('Welcher der acht Planeten hat die höchste mittlere Oberflächentemperatur?','Venus',2),('Welcher Planet hat laut NASA am Äquator die höchste Fallbeschleunigung?','Jupiter',3),('Welcher der acht Planeten besitzt die geringste Masse?','Merkur',2),('Welcher Planet hat laut NASA die größte Fluchtgeschwindigkeit?','Jupiter',4),('Welcher Planet hat eine mittlere Dichte unter der von Wasser (1000 kg/m³)?','Saturn',3),('Bei welchem Planeten liegt laut NASA ein Umlauf um die Sonne näher an 165 als an 100 Erdenjahren?','Neptun',4)]: clue('Weltraum',q,a,NASA,d)
for q,a,d in [('Wie viele Sekunden sind drei Minuten?','180',1),('Wie viele Zentimeter ergeben 2,5 Meter?','250',1),('Wie viele Millimeter sind 0,75 Meter?','750',2),('Wie viele Kubikzentimeter enthält ein Würfel mit 10 Zentimetern Kantenlänge?','1000',3),('Wie viele Quadratmeter umfasst ein Quadrat mit 12 Metern Seitenlänge?','144',2),('Wie viele Meter legt man in 10 Sekunden bei konstant 25 m/s zurück?','250',3),('Wie viele Watt entsprechen 2,5 Kilowatt?','2500',2),('Wie viele Kilogramm entsprechen 750 Gramm?','0,75',1)]: clue('Mix',q,a,NIST,d)
for q,a,source,d in [('In welchem Jahr begann der Erste Weltkrieg?','1914','https://www.dhm.de/lemo/kapitel/erster-weltkrieg',1),('In welchem Jahr endete der Erste Weltkrieg?','1918','https://www.dhm.de/lemo/kapitel/erster-weltkrieg',2),('In welchem Monat 1918 endete der Erste Weltkrieg?','November','https://www.dhm.de/lemo/kapitel/erster-weltkrieg',3),('Der deutsche Überfall auf welches Land begann am 1. September 1939?','Polen','https://www.dhm.de/lemo/kapitel/der-zweite-weltkrieg/kriegsverlauf/ueberfall-auf-polen-1939',1),('In welcher Stadt wurde das Grundgesetz am 23. Mai 1949 verkündet?','Bonn','https://www.hdg.de/lemo/jahreschronik/1949',3),('Welches Forschungsnetzwerk wurde laut LeMO im März 1949 in München gegründet?','Fraunhofer-Gesellschaft','https://www.hdg.de/lemo/jahreschronik/1949',5)]: clue('Geschichte',q,a,source,d)
for name,club,source in [('Jonathan Tah','Bayern München','https://fcbayern.com/de/news/2025/05/neuzugang-aus-leverkusen-jonathan-tah-kommt-zum-fc-bayern'),('Marcus Rashford','Barcelona','https://www.fcbarcelona.com/en/football/first-team/news/4319297'),('Leroy Sané','Galatasaray','https://www.galatasaray.org/haber/futbol/galatasaraya-hos-geldin-leroy-sane/57952'),('Kevin De Bruyne','SSC Neapel','https://live.mancity.com/news/mens/de-bruyne-to-join-napoli-63885336')]:
 clue('Transfers 2025',f'Zu welchem Verein '+('wurde' if name=='Marcus Rashford' else 'wechselte')+f' {name} im Sommer 2025'+(' ausgeliehen?' if name=='Marcus Rashford' else '?'),club,source,3)
for q,a,source in [('Bis zu welchem Jahr läuft Marc Cucurellas im Juni 2026 angekündigter Real-Vertrag?','2032','https://www.realmadrid.com/es-ES/noticias/club/comunicados/comunicado-oficial-cucurella-15-06-2026'),('Welcher französische Innenverteidiger wurde am 18. Juni 2026 von Real Madrid als Neuzugang angekündigt?','Ibrahima Konaté','https://www.realmadrid.com/es-ES/noticias/club/comunicados/comunicado-oficial-konate-18-06-2026'),('Welcher portugiesische Mittelfeldspieler wurde am 17. Juni 2026 von Real Madrid als Neuzugang angekündigt?','Bernardo Silva','https://www.realmadrid.com/es-ES/noticias/club/comunicados/comunicado-oficial-bernardo-silva-17-06-2026')]: clue('Transfers 2026',q,a,source,4)
# Fact-derived questions retain the reviewed primary sources and explicit historical cutoffs.
for f in trivia['facts']:
 if f.get('expansion')==5 and f['a'] and 'vor seinem Liverpool-Wechsel 2017' in f['s']:
  club=f['s'].split('für ')[-1].rstrip('.');clue('Vereinsstationen',f'Welcher Liverpool-Neuzugang von 2017 hatte zuvor für {club} gespielt?', 'Mohamed Salah',f['source'],3)
for name,country,ident in [('Aachener Dom','Deutschland',3),('Taj Mahal','Indien',252),('Opernhaus Sydney','Australien',166),('Kölner Dom','Deutschland',292),('Historisches Zentrum von Rom','Italien',91),('Machu Picchu','Peru',274),('Petra','Jordanien',326),('Angkor','Kambodscha',668)]: clue('Weltkultur',f'In welchem Land liegt die UNESCO-Welterbestätte {name}?',country,f'https://whc.unesco.org/en/list/{ident}/',2)
for q,a,d in [('Welcher Männer-Freiluft-Weltrekord hat im WA-Datensatz September 2026 die Zeit 43,03 Sekunden?','400 Meter',2),('Welcher Männer-Freiluft-Weltrekord hat im WA-Datensatz September 2026 die Zeit 100,91 Sekunden?','800 Meter',3),('Welcher Männer-Freiluft-Weltrekord hat im WA-Datensatz September 2026 die Zeit 206 Sekunden?','1500 Meter',4)]: clue('Rekorde & Extreme',q,a,'https://worldathletics.org/competitions/world-athletics-ultimate-championship/2026/news/news/world-record-watch-ultimate-championship',d)
# No rewording of an existing exact question is added by a repeated build.
seen={q['q'].strip().casefold() for q in trivia['jeopardy']}
for c in clues:
 if c['q'].strip().casefold() in seen: raise ValueError('Duplicate question: '+c['q'])
 seen.add(c['q'].strip().casefold())
trivia['jeopardy']+=clues
(ROOT/'content/catalogue.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
(ROOT/'content/trivia.json').write_text(json.dumps(trivia,ensure_ascii=False,indent=2)+'\n')
(ROOT/'content/research/2026-10-04/expansion-6.json').write_text(json.dumps(dict(numeric=newfacts,jeopardy=clues),ensure_ascii=False,indent=2)+'\n')
print('Added',len(newfacts),'numeric facts and',len(clues),'Jeopardy clues')
