import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
function setup(saved='{}',saveData=false){
 const nodes=new Map(),store=new Map([['ml_comfort_v1',saved],['ml_account_auth_v1','identity']]),listeners=new Map(),windowListeners=new Map(),classes=new Set();let calls=0,resolvePlay=null;let game={muted:false,volume:.35,reducedMotion:false};
 class Node{constructor(tag='div'){this.tagName=tag.toUpperCase();this.events={};this.paused=true;this.checked=false;this.value='';this.children=[];this.open=false}set id(x){this._id=x;nodes.set(x,this)}get id(){return this._id}set innerHTML(s){for(const m of s.matchAll(/<(input|button|output|p|h2)[^>]*id="([^"]+)"[^>]*>/g)){const n=new Node(m[1]);n.id=m[2];n.type=/type="([^"]+)"/.exec(m[0])?.[1];this.children.push(n)}}setAttribute(){}append(...n){this.children.push(...n)}addEventListener(k,f){this.events[k]=f}querySelectorAll(){return this.children.filter(n=>n.tagName==='INPUT')}showModal(){this.open=true}close(){this.open=false}pause(){this.paused=true}play(){calls++;return new Promise(r=>{resolvePlay=()=>{this.paused=false;r()}})}}
 const node=id=>{if(!nodes.has(id)){const n=new Node();n.id=id}return nodes.get(id)};
 const doc={hidden:false,currentScript:{src:'https://game.test/assets/comfort.js'},body:new Node(),documentElement:{classList:{toggle(k,v){v?classes.add(k):classes.delete(k)}}},createElement:t=>new Node(t),getElementById:node,querySelector:s=>s.includes('gamePreferences')?node('preferences'):null,querySelectorAll:()=>[],addEventListener:(k,f)=>listeners.set(k,f)};
 const win={getGamePreferences:()=>({...game}),applyGamePreferences:v=>{game=v;windowListeners.get('gamepreferenceschange')?.()},addEventListener:(k,f)=>windowListeners.set(k,f)};
 vm.runInNewContext(fs.readFileSync('assets/comfort.js','utf8'),{navigator:{connection:{saveData}},document:doc,window:win,localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},URL});
 return {node,doc,store,classes,listeners,calls:()=>calls,resolve:()=>resolvePlay?.(),win,change:()=>node('comfortMusic').events.change()};
}
const s=setup();assert.equal(s.calls(),0,'no default music autoplay');s.node('comfortMusic').checked=true;s.node('comfortMusicVolume').value=22;s.change();assert.equal(s.calls(),1);assert.equal(s.node('gameMusic').volume,.22);
s.node('comfortSound').checked=false;s.change();assert.equal(s.node('gameMusic').paused,true,'global mute pauses music');s.resolve();await new Promise(r=>setImmediate(r));assert.equal(s.node('gameMusic').paused,true,'late play cannot undo mute');
s.node('comfortSound').checked=true;s.node('comfortText').checked=true;s.node('comfortContrast').checked=true;s.change();s.resolve();await new Promise(r=>setImmediate(r));assert(s.classes.has('comfortLargeText'));assert(s.classes.has('comfortContrast'));assert.equal(s.store.get('ml_account_auth_v1'),'identity');
s.doc.hidden=true;s.listeners.get('visibilitychange')();assert.equal(s.node('gameMusic').paused,true);s.doc.hidden=false;s.listeners.get('visibilitychange')();assert.equal(s.calls(),3);s.resolve();await new Promise(r=>setImmediate(r));assert.equal(s.node('gameMusic').paused,false);const hidden=setup(s.store.get('ml_comfort_v1'));assert.equal(hidden.calls(),0,'saved music requires an interaction');assert.equal(hidden.node('comfortMusic').checked,true);assert.equal(hidden.node('comfortMusicVolume').value,22);assert.equal(setup('{bad').calls(),0);
const compact=setup();compact.node('comfortDataSaving').checked=true;compact.change();assert(compact.classes.has('dataSaving'));assert.equal(JSON.parse(compact.store.get('ml_comfort_v1')).dataSaving,true);assert(setup(compact.store.get('ml_comfort_v1')).classes.has('dataSaving'));assert(setup('{}',true).classes.has('dataSaving'),'honor browser Save-Data by default');assert(!setup('{"dataSaving":false}',true).classes.has('dataSaving'),'explicit preference overrides connection default');compact.node('comfortDataSaving').checked=false;compact.change();assert(!compact.classes.has('dataSaving'));
console.log('OK: music opt-in, separate volume, mute during pending play, device restoration and unchanged identity');
