import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const nodes=new Map(),events=new Map();let auth={uid:'first',guest:false},data={balance:200,music:'music-game-night',frame:'frame-david',name_color:'color-cyan',title:'title-chaos',title_name:'Chaosbeauftragter',catalog:[{id:'music-night-drive',kind:'music',name:'Night Drive',price:60,owned:false},{id:'frame-david',kind:'frame',name:'Davidstern',price:80,owned:true}]},pending=null,muted=true;
class Node{constructor(tag='div'){this.tagName=tag;this.children=[];this.dataset={};this.events={};this.style={setProperty:(k,v)=>this.style[k]=v};this.open=false;this.paused=true}set id(x){this._id=x;nodes.set(x,this)}get id(){return this._id}set innerHTML(s){for(const m of s.matchAll(/id="([^"]+)"/g)){const n=new Node();n.id=m[1]}}setAttribute(){}removeAttribute(){}append(...n){this.children.push(...n)}replaceChildren(...n){this.children=n}addEventListener(k,f){this.events[k]=f}focus(){}showModal(){this.open=true}close(){this.open=false;this.events.close?.()}pause(){this.paused=true}play(){this.paused=false;return Promise.resolve()}}
for(const id of ['accountProfileAvatar','accountAvatar','accountProfileName','accountDockName','accountPlayerTitle','accountDockTitle']){const n=new Node();n.id=id}
const win={accountReady:Promise.resolve(),gameAccount:{current:async()=>auth,authorized:async()=>pending?await pending:structuredClone(data)},dispatchEvent:e=>events.get(e.type)?.(),addEventListener:(k,f)=>events.set(k,f),getGamePreferences:()=>({muted})};const doc={currentScript:{src:'https://game.test/assets/economy.js'},body:new Node(),createElement:t=>new Node(t),getElementById:id=>nodes.get(id),addEventListener(){}};
vm.runInNewContext(fs.readFileSync('assets/audio/tracks.js','utf8'),{window:win});
vm.runInNewContext(fs.readFileSync('assets/economy.js','utf8'),{window:win,document:doc,URL,Event,setTimeout,clearTimeout,Error});
await win.gameEconomy.profile();assert.equal(nodes.get('accountPlayerTitle').textContent,'Chaosbeauftragter');assert.equal(nodes.get('accountAvatar').dataset.frame,'david');assert.match(nodes.get('accountAvatar').style['--frame-art'],/frames\/david.svg/);assert.equal(win.gameEconomy.owned('music-night-drive'),false);await assert.rejects(win.gameEconomy.equipMusic('music-night-drive'),/freischalten/);
const music=nodes.get('gameShopItems').children[0];await music.children.find(n=>n.textContent==='8 Sekunden anhören').onclick();assert.match(nodes.get('gameShopStatus').textContent,/Spielton/);assert.equal(doc.body.children[1].paused,true,'muted preview remains paused');
let release;pending=new Promise(r=>release=r);const flight=win.gameEconomy.profile();await new Promise(r=>setImmediate(r));auth={uid:'second',guest:false};win.gameEconomy.syncAccount(auth);release(data);await assert.rejects(flight,/Zugang/);pending=null;assert.equal(win.gameEconomy.data,null);assert.equal(nodes.get('accountPlayerTitle').hidden,true);assert.equal(nodes.get('accountAvatar').dataset.frame,'starter');
data={...data,music:'music-night-drive',catalog:[{...data.catalog[0],owned:true}]};await win.gameEconomy.profile();await win.gameEconomy.equipMusic('music-night-drive');assert.equal(win.gameEconomy.source('music-night-drive'),'https://game.test/assets/audio/night-drive.mp3');assert.equal(win.gameEconomy.source('../../unknown'),null);
console.log('OK: shop rendering, owned music gating, muted previews, title/frame application and account-race isolation');
