begin;
do $test$
declare host uuid:=gen_random_uuid(); guest uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid(); editor uuid:=gen_random_uuid();rid uuid;code text;state jsonb;cfg jsonb;edited jsonb;qid uuid;answer text;claimcode text:=repeat('a',48);pool jsonb;
begin
 insert into auth.users(id,aud,role,is_anonymous) values(host,'authenticated','authenticated',true),(guest,'authenticated','authenticated',true),(outsider,'authenticated','authenticated',true);
 insert into auth.users(id,aud,role,is_anonymous,email,email_confirmed_at,raw_app_meta_data) values(editor,'authenticated','authenticated',false,'fixture-editor@example.invalid',now(),'{}');
 perform set_config('request.jwt.claim.sub',host::text,true);
 select room_id,room_code into rid,code from public.ml_create_room('Host','{"game":"moreless","game_mode":"CLASSIC","custom_rules":{"correct_points":3,"wrong_penalty":2,"lives":5,"jokers":false}}');
 select config into cfg from public.rooms where id=rid;
 if (cfg->'custom_rules'->>'lives')::int<>5 or (cfg->>'joker_enabled')::boolean then raise exception 'create rule validation';end if;
 begin perform public.ml_set_custom_rules(rid,'{"lives":0}');raise exception 'invalid lives accepted';exception when others then if sqlerrm<>'invalid rules' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',guest::text,true);perform public.ml_join_room(code,'Guest');
 begin perform public.ml_set_custom_rules(rid,'{}');raise exception 'guest changed rules';exception when others then if sqlerrm<>'host only' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',host::text,true);
 perform public.ml_online_ml_start(rid,1,'Test','height','Which?','m','A','',100,'B','',50,45);
 perform public.ml_online_ml_submit(rid,1,'a');
 perform set_config('request.jwt.claim.sub',guest::text,true);perform public.ml_online_ml_submit(rid,1,'b');
 if (select score from public.players where room_id=rid and user_id=host)<>3 or (select score from public.players where room_id=rid and user_id=guest)<>-2 then raise exception 'custom points mismatch';end if;
 if (select lives from ml_private.online_mode_players where room_id=rid and user_id=host)<>5 then raise exception 'custom lives mismatch';end if;
 perform set_config('request.jwt.claim.sub',host::text,true);
 begin perform public.ml_set_custom_rules(rid,'{}');raise exception 'rules changed during match';exception when others then if sqlerrm<>'Settings locked after game start' then raise;end if;end;
 -- Direct table never contains answers; every action and snapshot applies the same mask.
 perform public.jeopardy_init(rid);perform public.jeopardy_open_question(rid,0,0,100,'Test','Private solution?','secret-fixture');
 if exists(select 1 from public.jeopardy_game_state where room_id=rid and selected_answer is not null) then raise exception 'table leak';end if;
 if public.ml_jeopardy_state(rid)->>'selected_answer'<>'secret-fixture' then raise exception 'host lost solution';end if;
 perform set_config('request.jwt.claim.sub',guest::text,true);
 if (to_jsonb(public.jeopardy_init(rid))->>'selected_answer') is not null or (public.ml_jeopardy_state(rid)->>'selected_answer') is not null then raise exception 'member solution leak';end if;
 perform set_config('request.jwt.claim.sub',outsider::text,true);
 begin perform public.ml_jeopardy_state(rid);raise exception 'outsider read state';exception when others then if sqlerrm<>'not room member' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',host::text,true);perform public.jeopardy_finish(rid);
 perform set_config('request.jwt.claim.sub',guest::text,true);
 if public.ml_jeopardy_state(rid)->>'selected_answer'<>'secret-fixture' then raise exception 'reveal unavailable';end if;
 begin perform public.ml_content_editor('list');raise exception 'guest editor';exception when others then if sqlerrm<>'Redaktionszugang erforderlich' then raise;end if;end;
 insert into ml_private.editor_activation(code_hash,expires_at) values(encode(extensions.digest(claimcode,'sha256'),'hex'),now()+interval '1 hour');
 begin perform public.ml_activate_editor(claimcode);raise exception 'anonymous claimed editor';exception when others then if sqlerrm<>'Bitte zuerst einen festen Account mit bestätigter E-Mail anmelden.' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',editor::text,true);perform public.ml_activate_editor(claimcode);
 edited:=public.ml_content_editor('save','{"id":"estimate:fixture123","game":"estimate","payload":{"q":"Test?","a":10,"u":"m","source":"https://example.invalid","verified":"2026-10-09"}}');
 if jsonb_array_length(public.ml_content_published()->'entries')<>0 then raise exception 'draft leaked';end if;
 edited:=public.ml_content_editor('publish',jsonb_build_object('id','estimate:fixture123','version',edited->'version'));
 if (public.ml_content_published()->'entries'->0->'payload'->>'a')::int<>10 then raise exception 'publish lost payload';end if;
 begin perform public.ml_content_editor('save','{"id":"estimate:fixture123","version":0,"game":"estimate","payload":{"q":"Test?","a":11,"u":"m","source":"https://example.invalid","verified":"2026-10-09"}}');raise exception 'stale edit allowed';exception when others then if sqlerrm<>'Entwurf wurde inzwischen geändert. Neu laden.' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',host::text,true);perform public.ml_online_reset(rid);update public.rooms set config=config||'{"game_mode":"SORT"}'::jsonb where id=rid;
 pool:='[{"category":"Test","metric":"height","unit":"m","cards":[{"name":"A","value":10},{"name":"B","value":20},{"name":"C","value":30},{"name":"D","value":40}]}]';
 state:=public.ml_sort_duel(rid,'start',jsonb_build_object('pool',pool));qid:=(state->>'question_id')::uuid;
 if state->'cards'->0 ? 'value' or state->'result'<>'null'::jsonb then raise exception 'sort value leaked';end if;
 begin perform public.ml_sort_duel(rid,'submit',jsonb_build_object('question_id',qid,'order','[0,1,2,3]'::jsonb));raise exception 'preview not locked';exception when others then if sqlerrm<>'question not accepting answers' then raise;end if;end;
 update ml_private.sort_matches set starts_at=clock_timestamp()-interval '1 second' where room_id=rid;
 state:=public.ml_sort_duel(rid,'submit',jsonb_build_object('question_id',qid,'order','[0,1,2,3]'::jsonb));
 if state->'result'<>'null'::jsonb then raise exception 'sort early reveal';end if;
 perform set_config('request.jwt.claim.sub',guest::text,true);
 begin perform public.ml_sort_duel(rid,'submit',jsonb_build_object('question_id',qid,'order','[0,0,2,3]'::jsonb));raise exception 'duplicate positions allowed';exception when others then if sqlerrm<>'invalid order' then raise;end if;end;
 state:=public.ml_sort_duel(rid,'submit',jsonb_build_object('question_id',qid,'order','[3,2,1,0]'::jsonb));
 if state->>'phase'<>'revealed' or (state->'stats'->host::text->>'score')::int<>6 or (state->'stats'->guest::text->>'score')::int<>0 then raise exception 'sort scoring';end if;
 begin perform public.ml_sort_duel(rid,'next');raise exception 'guest advanced';exception when others then if sqlerrm<>'host only' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',host::text,true);state:=public.ml_sort_duel(rid,'next');if state->>'phase'<>'finished' then raise exception 'sort did not finish';end if;
 perform public.ml_online_reset(rid);if exists(select 1 from ml_private.sort_matches where room_id=rid) then raise exception 'sort survived reset';end if;
end $test$;
rollback;
select 'PASS: answer privacy, rules, editor authorization and versioning, sorting privacy and scoring; fixtures rolled back' verification;
