begin;
do $test$
declare u uuid:=gen_random_uuid();v uuid:=gen_random_uuid();w uuid:=gen_random_uuid();rid uuid;code text;state jsonb;
begin
 insert into auth.users(id,aud,role) values(u,'authenticated','authenticated'),(v,'authenticated','authenticated'),(w,'authenticated','authenticated');
 perform set_config('request.jwt.claim.sub',u::text,true);
 select room_id,room_code into rid,code from public.ml_create_room('Ready Host','{"game":"moreless","game_mode":"CLASSIC"}'::jsonb);
 perform set_config('request.jwt.claim.sub',v::text,true);perform public.ml_join_room(code,'Ready Guest');
 perform set_config('request.jwt.claim.sub',w::text,true);
 begin perform public.ml_lobby_ready(rid,true);raise exception 'non-member allowed';exception when others then if sqlerrm<>'Nur Mitspieler dieser Lobby dürfen diese Aktion ausführen.' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',u::text,true);state:=public.ml_lobby_ready(rid,true);
 if jsonb_array_length(state->'members')<>2 then raise exception 'wrong roster';end if;
 begin perform public.ml_online_ml_start(rid,1,'Test','Test','Test','km','A','',1,'B','',2,45);raise exception 'unready start allowed';exception when others then if sqlerrm<>'Noch nicht alle bereit. Prüfe die Lobby.' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',v::text,true);perform public.ml_lobby_ready(rid,true);
 -- A team selection invalidates just the player's readiness.
 insert into public.online_team_members(room_id,user_id,team_no) values(rid,v,1);
 state:=public.ml_lobby_ready(rid);
 if exists(select 1 from jsonb_array_elements(state->'members') x where x->>'user_id'=v::text and (x->>'ready')::boolean) then raise exception 'team change retained ready';end if;
 perform public.ml_lobby_ready(rid,true);
 perform set_config('request.jwt.claim.sub',u::text,true);perform public.ml_update_room_settings(rid,2,8,32);
 if exists(select 1 from ml_private.lobby_readiness where room_id=rid) then raise exception 'rules change retained ready';end if;
 perform public.ml_lobby_ready(rid,true);perform set_config('request.jwt.claim.sub',v::text,true);perform public.ml_lobby_ready(rid,true);
 begin perform public.ml_lobby_setup(rid,'estimate','classic');raise exception 'guest setup allowed';exception when others then if sqlerrm<>'Nur der Host kann das Spiel ändern.' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',u::text,true);perform public.ml_lobby_setup(rid,'moreless','CHAOS');
 if exists(select 1 from ml_private.lobby_readiness where room_id=rid) then raise exception 'mode change retained ready';end if;
 perform public.ml_lobby_ready(rid,true);perform set_config('request.jwt.claim.sub',v::text,true);perform public.ml_lobby_ready(rid,true);
 perform set_config('request.jwt.claim.sub',u::text,true);perform public.ml_online_ml_start(rid,1,'Test','Test','Test','km','A','',1,'B','',2,45);
 if (select status from public.rooms where id=rid)<>'playing' then raise exception 'ready start failed';end if;
 begin perform public.ml_lobby_ready(rid,false);raise exception 'midgame ready allowed';exception when others then if sqlerrm<>'Die Runde läuft bereits.' then raise;end if;end;
 perform public.ml_online_reset(rid);
 if exists(select 1 from ml_private.lobby_readiness where room_id=rid) then raise exception 'rematch retained ready';end if;
 perform public.ml_lobby_setup(rid,'facts','classic');
 begin perform public.ml_fact_game(rid,'start');raise exception 'unready fact start allowed';exception when others then if sqlerrm<>'Noch nicht alle bereit. Prüfe die Lobby.' then raise;end if;end;
 perform public.ml_lobby_ready(rid,true);perform set_config('request.jwt.claim.sub',v::text,true);perform public.ml_lobby_ready(rid,true);
 perform set_config('request.jwt.claim.sub',u::text,true);perform public.ml_fact_game(rid,'start');
 if (select status from public.rooms where id=rid)<>'playing' then raise exception 'fact room stayed in lobby';end if;
 perform public.ml_fact_game(rid,'reset');perform public.ml_online_reset(rid);
 perform public.ml_lobby_setup(rid,'estimate','classic');
 begin perform public.ml_estimate_start(rid,'classic',(select jsonb_agg(jsonb_build_object('q','Test '||i,'a',i,'u','m')) from generate_series(1,10) i));raise exception 'unready estimate start allowed';exception when others then if sqlerrm<>'Noch nicht alle bereit. Prüfe die Lobby.' then raise;end if;end;
 perform public.ml_lobby_ready(rid,true);perform set_config('request.jwt.claim.sub',v::text,true);perform public.ml_lobby_ready(rid,true);
 perform set_config('request.jwt.claim.sub',u::text,true);perform public.ml_estimate_start(rid,'classic',(select jsonb_agg(jsonb_build_object('q','Test '||i,'a',i,'u','m')) from generate_series(1,10) i));
 if (select status from public.rooms where id=rid)<>'playing' then raise exception 'estimate start failed';end if;
 perform public.ml_online_reset(rid);
 perform public.ml_lobby_setup(rid,'quiz','standard');
 begin perform public.ml_online_ml_start(rid,901,'standard','JEOPARDY_START','JEOPARDY_START','start','START','',1,'START','',1,45);raise exception 'unready jeopardy start allowed';exception when others then if sqlerrm<>'Noch nicht alle bereit. Prüfe die Lobby.' then raise;end if;end;
 perform public.ml_lobby_ready(rid,true);perform set_config('request.jwt.claim.sub',v::text,true);perform public.ml_lobby_ready(rid,true);
 perform set_config('request.jwt.claim.sub',u::text,true);perform public.ml_online_ml_start(rid,901,'standard','JEOPARDY_START','JEOPARDY_START','start','START','',1,'START','',1,45);
 if (select status from public.rooms where id=rid)<>'playing' then raise exception 'jeopardy start failed';end if;
 perform public.ml_online_reset(rid);
 begin perform public.ml_lobby_remove(rid,v);raise exception 'active member removed';exception when others then if sqlerrm<>'Dieser Mitspieler ist noch verbunden.' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',v::text,true);
 begin perform public.ml_lobby_remove(rid,u);raise exception 'guest removal allowed';exception when others then if sqlerrm<>'Nur der Host kann Mitspieler entfernen.' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',u::text,true);
 update public.players set connected=false where room_id=rid and user_id=v;
 perform public.ml_lobby_remove(rid,v);
 if (select count(*) from public.players where room_id=rid)<>1 then raise exception 'disconnected removal failed';end if;
 if has_function_privilege('anon','public.ml_lobby_ready(uuid,boolean)','EXECUTE') or has_table_privilege('authenticated','ml_private.lobby_readiness','SELECT') then raise exception 'readiness access exposed';end if;
end $test$;
rollback;
