begin;
create temp table medium_users(n int primary key,id uuid default gen_random_uuid());
insert into medium_users(n) values(1),(2),(3);
insert into auth.users(id,aud,role,is_anonymous) select id,'authenticated','authenticated',true from medium_users;
create temp table medium_room(id uuid default gen_random_uuid());insert into medium_room default values;
insert into public.rooms(id,code,host_user_id,config) select id,upper(substr(replace(id::text,'-',''),1,6)),(select id from medium_users where n=1),'{"game":"facts","game_mode":"classic"}' from medium_room;
insert into public.players(room_id,user_id,display_name,seat) select r.id,u.id,'Fixture '||n,n from medium_room r cross join medium_users u where n<=2;
insert into public.ml_profiles(user_id,handle,display_name) select id,'fixture_'||substr(replace(id::text,'-',''),1,12),'Fixture '||n from medium_users;
insert into public.ml_friendships(sender_id,recipient_id,status) select a.id,b.id,'accepted' from medium_users a,medium_users b where a.n=1 and b.n=2;
insert into ml_private.daily_attempts(day,user_id,name,answered,score,completed_at,game) select date '1901-01-07',id,'Fixture '||n,5,case when n=3 then 600 else 500 end,case when n=3 then timestamptz '1901-01-09 12:00:00+00' else timestamptz '1901-01-07 12:00:00+00' end,'moreless' from medium_users;
grant select on medium_users,medium_room to authenticated;
select set_config('request.jwt.claim.sub',(select id::text from medium_users where n=1),true);
set local role authenticated;
do $$declare a jsonb;b jsonb;blocked boolean;begin
 a:=public.ml_player_hub('history_mark','{"facts":["fixture A","fixture B"]}');assert jsonb_array_length(a->'facts')=2,'history stored';
 b:=public.ml_player_hub('history_mark','{"facts":["fixture A"]}');assert jsonb_array_length(b->'facts')=2,'deduplicated history';
 a:=public.ml_player_hub('record','{"run_id":"fixture","game":"facts","mode":"classic","score":4,"answered":10,"correct":4,"best_streak":3}');
 a:=public.ml_player_hub('record','{"run_id":"fixture","game":"facts","mode":"classic","score":9,"answered":10,"correct":9,"best_streak":9}');
 a:=public.ml_player_hub('profile');assert (a->'runs'->0->>'runs')::int=1 and (a->'runs'->0->>'best_score')::int=4,'run retry keeps first value';
 assert jsonb_array_length(a->'daily')=1,'Daily progress';assert jsonb_array_length(a->'rewards')=2,'daily and weekly reward';assert (a->'rewards'->0->>'rank')::int=1,'tie gold';
 a:=public.ml_player_hub('board','{"game":"moreless","day":"1901-01-07","period":"week","scope":"friends"}');assert (a->>'total')::int=2,'accepted friends only, late archive excluded';assert (a->'leaderboard'->1->>'rank')::int=1,'ties rank equal';
 blocked:=false;begin perform public.ml_player_hub('record','{"game":"facts"}');exception when others then blocked:=true;end;assert blocked,'missing fields rejected';
 blocked:=false;begin perform * from ml_private.player_runs;exception when insufficient_privilege then blocked:=true;end;assert blocked,'raw results inaccessible';
 blocked:=false;begin perform * from ml_private.fact_matches;exception when insufficient_privilege then blocked:=true;end;assert blocked,'secret answers inaccessible';
 a:=public.ml_fact_game((select id from medium_room),'start');assert a->>'phase'='open','host starts';assert (a->'waitingStatus'->>'active')::boolean,'waiting snapshot active';assert jsonb_array_length(a->'waitingStatus'->'players')=2,'roster only';assert not(a->'waitingStatus'->'players'->0 ? 'choice') and not(a->'waitingStatus'->'players'->0 ? 'answer'),'waiting never exposes choices';assert not(a->'question' ? 'a') and a->'result'='null','answer hidden';
 a:=public.ml_fact_game((select id from medium_room),'answer',(a->>'question_id')::uuid,false);assert (a->'mine'->>'choice')::boolean=false,'false answer stored';
 b:=public.ml_fact_game((select id from medium_room),'answer',(a->>'question_id')::uuid,true);assert (b->'mine'->>'choice')::boolean=false,'changed retry cannot overwrite';
 blocked:=false;begin perform public.ml_fact_game((select id from medium_room),'next',(a->>'question_id')::uuid);exception when others then blocked:=true;end;assert blocked,'reveal first';
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from medium_users where n=2),true);
set local role authenticated;
do $$declare a jsonb;b jsonb;blocked boolean;begin
 a:=public.ml_player_hub('history');assert not(a->'facts' ? 'fixture A') and jsonb_array_length(a->'facts')=10,'own online history excludes other caller history';
 a:=public.ml_fact_game((select id from medium_room),'state');b:=public.ml_fact_game((select id from medium_room),'answer',(a->>'question_id')::uuid,false);assert b->>'phase'='revealed','both players resolve';
 a:=public.ml_fact_game((select id from medium_room),'state');assert a->'scores'=b->'scores','no repeated score';assert a->'result'->'answer'<>'null','truth after reveal';
 blocked:=false;begin perform public.ml_fact_game((select id from medium_room),'next',(a->>'question_id')::uuid);exception when others then blocked:=true;end;assert blocked,'guest cannot advance';
 blocked:=false;begin perform public.ml_fact_game((select id from medium_room),'reset');exception when others then blocked:=true;end;assert blocked,'guest cannot reset';
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from medium_users where n=1),true);
set local role authenticated;
do $$declare a jsonb;b jsonb;blocked boolean;begin
 a:=public.ml_fact_game((select id from medium_room),'state');b:=public.ml_fact_game((select id from medium_room),'next',(a->>'question_id')::uuid);assert (b->>'index')::int=1 and b->>'question_id'<>a->>'question_id','host advances everyone';
 blocked:=false;begin perform public.ml_fact_game((select id from medium_room),'answer',(a->>'question_id')::uuid,true);exception when others then blocked:=true;end;assert blocked,'stale question rejected';
end $$;
reset role;
update ml_private.fact_matches set deadline=clock_timestamp()-interval '1 second' where room_id=(select id from medium_room);
set local role authenticated;
do $$declare a jsonb;begin a:=public.ml_fact_game((select id from medium_room),'state');assert a->>'phase'='revealed' and (a->'result'->'answers'->0->>'timeout')::boolean,'timeout resolves';end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from medium_users where n=3),true);
set local role authenticated;
do $$declare blocked boolean:=false;begin begin perform public.ml_fact_game((select id from medium_room),'state');exception when others then blocked:=true;end;assert blocked,'nonmember excluded';end $$;
reset role;
set local role anon;
do $$declare blocked boolean:=false;begin begin perform public.ml_player_hub('profile');exception when insufficient_privilege then blocked:=true;end;assert blocked,'anon role cannot use hub';blocked:=false;begin perform public.ml_fact_game(gen_random_uuid(),'state');exception when insufficient_privilege then blocked:=true;end;assert blocked,'anon cannot use Fact/Fake RPC';end $$;
reset role;
select 'medium_assertions_passed' as result;
rollback;
