begin;
select set_config('mp.a',gen_random_uuid()::text,true),set_config('mp.b',gen_random_uuid()::text,true),set_config('mp.room',gen_random_uuid()::text,true),set_config('mp.q',gen_random_uuid()::text,true);
insert into auth.users(id,aud,role,is_anonymous) select current_setting('mp.'||x)::uuid,'authenticated','authenticated',true from unnest(array['a','b']) x;
insert into ml_private.cosmetic_wallet(user_id,balance) select current_setting('mp.'||x)::uuid,500 from unnest(array['a','b']) x;
insert into ml_private.login_claims values(current_setting('mp.b')::uuid,(clock_timestamp() at time zone 'Europe/Berlin')::date-1,6,20);
insert into public.rooms(id,code,host_user_id,status,phase,config) values(current_setting('mp.room')::uuid,upper(substr(replace(current_setting('mp.room'),'-',''),1,6)),current_setting('mp.a')::uuid,'playing','reveal','{"game_mode":"SURVIVAL","rounds":6,"questions_per_round":5}');
insert into public.players(room_id,user_id,display_name,seat) select current_setting('mp.room')::uuid,current_setting('mp.'||x)::uuid,'Test',case x when 'a' then 1 else 2 end from unnest(array['a','b']) x;
insert into ml_private.online_mode_players(room_id,user_id,lives) select current_setting('mp.room')::uuid,current_setting('mp.'||x)::uuid,case x when 'a' then 0 else 2 end from unnest(array['a','b']) x;
insert into public.online_ml_questions(room_id,question_no,category,metric,prompt,unit,left_name,right_name,status,question_id) values(current_setting('mp.room')::uuid,1,'Test','metric','Test?','m','A','B','revealed',current_setting('mp.q')::uuid);
insert into public.online_ml_reveals(room_id,question_no,results) values(current_setting('mp.room')::uuid,1,'{"game_over":false,"answers":[]}');
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('mp.a'),'role','authenticated')::text,true);
do $$declare p jsonb;t uuid;begin
 p:=public.ml_cosmetics('login');if (p->>'balance')::int<>520 or (p->>'login_reward')::int<>20 then raise exception 'Login claim incorrect: %',p;end if;
 if (public.ml_cosmetics('login')->>'balance')::int<>520 then raise exception 'Duplicate login reward';end if;
 p:=public.ml_cosmetics('buy','music-neon-drive');if (p->>'balance')::int<>360 or p->>'background_music'<>'music-neon-drive' then raise exception 'Music purchase failed';end if;
 if (public.ml_cosmetics('buy','music-neon-drive')->>'balance')::int<>360 then raise exception 'Repeated purchase charged';end if;
 begin perform public.ml_cosmetics('equip','win-gold-rush');raise exception 'Unowned win equip';exception when others then if sqlerrm<>'Dieses Item besitzt du noch nicht.' then raise;end if;end;
 p:=public.ml_progression('start_solo','facts');t:=(p->>'token')::uuid;perform set_config('mp.solo',t::text,true);
 p:=public.ml_progression('continue_solo',null,null,t);if (p->>'balance')::int<>320 then raise exception 'Solo rescue price';end if;
 p:=public.ml_progression('continue_solo',null,null,t);if not (p->>'already_paid')::boolean then raise exception 'Rescue retry not idempotent';end if;
 begin perform public.ml_progression('revive_ml',null,current_setting('mp.room')::uuid,gen_random_uuid());raise exception 'Stale question accepted';exception when others then if sqlerrm not like 'Die Frage hat gewechselt.%' then raise;end if;end;
 p:=public.ml_progression('revive_ml',null,current_setting('mp.room')::uuid,current_setting('mp.q')::uuid);if (p->>'balance')::int<>280 then raise exception 'Online rescue price';end if;
 if (public.ml_cosmetics()->>'balance')::int<>280 then raise exception 'Unexpected balance';end if;
 begin update ml_private.cosmetic_wallet set balance=99999;raise exception 'Wallet writable';exception when insufficient_privilege then null;end;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('mp.b'),'role','authenticated')::text,true);
do $$declare p jsonb;begin
 p:=public.ml_cosmetics('login');if (p->>'balance')::int<>570 or (p->>'login_reward')::int<>70 or (p->'login'->>'streak')::int<>7 then raise exception '7-day bonus incorrect';end if;
 begin perform public.ml_progression('continue_solo',null,null,current_setting('mp.solo')::uuid);raise exception 'Foreign rescue allowed';exception when others then if sqlerrm<>'Der Rettungsversuch ist abgelaufen.' then raise;end if;end;
 begin perform public.ml_progression('revive_ml',null,current_setting('mp.room')::uuid,current_setting('mp.q')::uuid);raise exception 'Healthy player resurrected';exception when others then if sqlerrm not like 'Rettung nur%' then raise;end if;end;
end $$;
reset role;
do $$begin if (select lives from ml_private.online_mode_players where room_id=current_setting('mp.room')::uuid and user_id=current_setting('mp.a')::uuid)<>1 then raise exception 'Life not restored';end if;end $$;
set local role anon;
do $$begin begin perform public.ml_progression('start_solo','facts');raise exception 'Anonymous API access';exception when insufficient_privilege then null;end;end $$;
reset role;
select 'PASS: login idempotency, seventh-day bonus, music ownership, purchase retry, paid solo retry, online rescue, stale token and ownership guards' result;
rollback;
