import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const nodes=new Map(),store=new Map();
class Node{constructor(){this.children=[];this.dataset={};this.hidden=false;this.textContent='';this.value='';this.parentElement=this}set id(v){this._id=v;nodes.set(v,this)}get id(){return this._id}set innerHTML(s){for(const m of s.matchAll(/id="([^"]+)"/g)){const n=new Node();n.id=m[1]}this.html=s}append(...x){this.children.push(...x)}before(){}replaceChildren(...x){this.children=x}querySelector(s){if(!this.parts)this.parts={};return this.parts[s]||=new Node()}classList={add(){},remove(){},contains(){return false}}}
const node=id=>{if(!nodes.has(id)){const n=new Node();n.id=id}return nodes.get(id)};
const ctx=vm.createContext({document:{createElement:()=>new Node(),getElementById:node},window:{getCosmeticCollection:()=>({owner:'owner',challenge_achievements:[]}),getGuestProfile:()=>({name:'Test'}),requestProgression:async()=>({token:'ticket'})},crypto:{randomUUID:()=>String(Math.random())},localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},GAME_WORLD:'facts',S:{room:null},SOLO:{},EST:{},FACT:{online:false,history:[],locked:false},FACT_Q:[],ESTIMATE_Q:[],factShuffle:x=>[...x],estimateDifficulty:x=>x.difficulty,reviewedFactPool:x=>x,openWorldMenu(){},playSolo(){},renderEstimate(){},submitEstimate(){ctx.EST.history.push({ok:false})},renderFact(){},answerFact(v){if(ctx.FACT.locked)return;ctx.FACT.locked=true;ctx.FACT.history.push({ok:v})},soloPick(){ctx.SOLO.history.push({ok:true})},showLocalEnd(){},showFinish:async()=>{},renderOnlineMode(){},renderEstimateOnline(){},hideLocalEnd(){},nextEstimate(){},renderSolo(){},spinSoloCategory(){},refreshOnlineModes:async()=>{},syncEstimateOnline:async()=>{},onlineTotalQuestions:()=>20,Math,Number,Set,Map,Object,String});
vm.runInContext(fs.readFileSync('assets/progression.js','utf8'),ctx);
node('challengeLength').value='30';node('challengeLength').onchange();const pool=Array.from({length:60},(_,i)=>({s:'q'+i,difficulty:i<20?'easy':i<40?'medium':'hard'}));assert.equal(ctx.window.challengeQuestions('facts',pool).length,30);
node('challengeLength').value='infinity';node('challengeLength').onchange();const ordered=ctx.window.challengeQuestions('facts',[...pool].reverse());assert.equal(ordered.length,60);assert.equal(new Set(ordered.map(q=>q.s)).size,60);assert.equal(ordered[0].difficulty,'easy');assert.equal(ordered.at(-1).difficulty,'hard');
ctx.window.beginChallengeRun('facts',ctx.FACT);await new Promise(r=>setImmediate(r));assert.equal(ctx.FACT.lives,3);assert.equal(ctx.FACT.rescueToken,'ticket');ctx.answerFact(false);assert.equal(ctx.FACT.lives,2);ctx.answerFact(false);assert.equal(ctx.FACT.lives,2,'double answer cannot consume another life');
ctx.GAME_WORLD='moreless';node('challengeLength').value='50';node('challengeLength').onchange();assert.equal(ctx.window.challengeRounds(),10);ctx.SOLO={mode:'BLITZ',history:Array.from({length:19},()=>({ok:true})),on:true};ctx.soloPick();assert(store.get('ml_practice_achievements_v1:owner').includes('practice-blitz-20'));
store.clear();ctx.SOLO={mode:'BLITZ',assisted:true,history:Array.from({length:19},()=>({ok:true})),on:true};ctx.soloPick();assert.equal(store.size,0,'assisted run cannot earn clean achievements');
ctx.EST={endless:true,mode:'classic',lives:3,history:[]};ctx.submitEstimate();assert.equal(ctx.EST.lives,2,'endless estimates lose lives too');
console.log('OK: 30/50 challenges, adaptive finite Endlos deck, one life per answer, rescue token, clean Blitz milestones and assisted exclusion');
